import {
  Database,
  Workflow,
  Eye,
  Users,
  TrendingUp,
  Send,
  LifeBuoy,
  ChartNoAxesCombined,
  Sparkles,
  Cpu,
  Compass,
  Search,
  Target,
  Megaphone,
  MessageSquare,
  Presentation,
  Store,
  HeartPulse,
  Hotel,
  Factory,
  Landmark,
  Briefcase,
  Heart,
  ShieldCheck,
  Network,
  BrainCircuit,
  Handshake,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

const icons: Readonly<Record<string, LucideIcon>> = {
  Database,
  Workflow,
  Eye,
  Users,
  TrendingUp,
  Send,
  LifeBuoy,
  ChartNoAxesCombined,
  Sparkles,
  Cpu,
  Compass,
  Search,
  Target,
  Megaphone,
  MessageSquare,
  Presentation,
  Store,
  HeartPulse,
  Hotel,
  Factory,
  Landmark,
  Briefcase,
  Heart,
  ShieldCheck,
  Network,
  BrainCircuit,
  Handshake,
};

export function CRMIcon({ name, className }: { name: string; className?: string }) {
  const Icon = icons[name] ?? HelpCircle;
  return <Icon className={className} aria-hidden="true" />;
}
