export type LegalGroup = { title: string; items: readonly string[] };
export type LegalSectionData = { id: string; title: string; paragraphs: readonly string[]; items?: readonly string[]; groups?: readonly LegalGroup[] };
export type LegalDocument = { slug: "privacy-policy" | "terms-of-service" | "security-policy"; title: string; subtitle: string; description: string; introduction: string; lastUpdated: string; sections: readonly LegalSectionData[] };

export const legalCompany = { name: "Brainzon", email: "info@brainzon.com", securityEmail: "security@brainzon.com", website: "https://www.brainzon.com", displayWebsite: "www.brainzon.com", lastUpdated: "2026-07-12", governingLaw: "the jurisdiction identified in the applicable order form, statement of work, or service agreement" } as const;

const privacyPolicy: LegalDocument = {
  slug: "privacy-policy", title: "Privacy Policy", subtitle: "Your privacy and trust are fundamental to everything we build.",
  description: "Learn how Brainzon collects, uses, protects, and manages personal information while delivering enterprise software, ERP, CRM, AI, and digital transformation services.", lastUpdated: legalCompany.lastUpdated,
  introduction: "Brainzon is committed to protecting the information entrusted to us by customers, partners, website visitors, and users. This policy explains the information we collect, why we use it, how we safeguard it, and the choices available to individuals.",
  sections: [
    { id: "information-we-collect", title: "Information We Collect", paragraphs: ["We collect information that you provide directly, information generated through your use of our website and services, and business information required to evaluate or deliver a solution."], groups: [
      { title: "Personal information", items: ["Name", "Email address", "Phone number", "Company information", "Business requirements"] },
      { title: "Technical information", items: ["Browser information", "Device information", "IP address", "Website usage data"] },
      { title: "Business information", items: ["Project requirements", "Software requirements", "Communication records"] },
    ] },
    { id: "how-we-use-information", title: "How We Use Information", paragraphs: ["We use information only for legitimate business, contractual, security, and service-delivery purposes."], items: ["Providing and administering services", "Responding to inquiries and support requests", "Arranging product demonstrations", "Improving products and solutions", "Managing customer communication", "Detecting risk and improving security"] },
    { id: "cookies", title: "Cookies and Tracking Technologies", paragraphs: ["Our website may use essential cookies and similar technologies for website operation, analytics, and user-experience improvement. Where required, optional technologies are used according to your consent or preferences.", "You can manage cookies through the preference controls made available on the website and through your browser settings. Blocking some cookies may affect specific website functionality."], items: ["Website analytics", "User-experience improvement", "Cookie preference management"] },
    { id: "data-sharing", title: "Data Sharing", paragraphs: ["Brainzon does not sell personal information. We may share limited information with parties that help us operate our business or meet legal obligations, subject to appropriate contractual and security controls."], items: ["Service providers supporting hosting, communication, analytics, or operations", "Technology partners involved in an authorized customer solution", "Legal, regulatory, or public authorities when disclosure is required by law"] },
    { id: "data-security", title: "Data Security", paragraphs: ["We apply administrative, technical, and organizational safeguards designed to protect information against unauthorized access, alteration, disclosure, or loss. No system can guarantee absolute security, and our controls are reviewed according to risk and service context."], items: ["Encryption where appropriate", "Identity and access controls", "Security monitoring", "Secure infrastructure and operational practices"] },
    { id: "data-retention", title: "Data Retention", paragraphs: ["We retain information only for as long as reasonably necessary for the purpose for which it was collected, subject to contractual, operational, and legal requirements. Information is deleted, anonymized, or securely archived when it is no longer required."], items: ["Business and project requirements", "Legal and regulatory obligations", "Service-delivery and support needs"] },
    { id: "user-rights", title: "User Rights", paragraphs: ["Depending on your location and applicable law, you may have rights concerning your personal information. We may need to verify your identity before completing a request and may retain information where legally permitted or required."], items: ["Request access to personal information", "Request correction of inaccurate information", "Request deletion", "Request restriction of certain processing", "Request information about how data is used or disclosed"] },
    { id: "contact", title: "Contact Information", paragraphs: ["For privacy questions or requests, contact Brainzon using the details below."], groups: [{ title: "Brainzon", items: [`Email: ${legalCompany.email}`, `Website: ${legalCompany.displayWebsite}`] }] },
  ],
};

const termsOfService: LegalDocument = {
  slug: "terms-of-service", title: "Terms of Service", subtitle: "Terms and conditions governing your relationship with Brainzon.",
  description: "Review Brainzon's terms and conditions for using our software solutions, consulting services, websites, and digital transformation offerings.", lastUpdated: legalCompany.lastUpdated,
  introduction: "These Terms of Service govern access to Brainzon websites, software solutions, consultations, and professional services. Project-specific order forms, statements of work, subscriptions, or license agreements may include additional terms and will control where they conflict with these general terms.",
  sections: [
    { id: "agreement", title: "Agreement to Terms", paragraphs: ["By accessing our website, requesting or receiving services, using a Brainzon software solution, or participating in a consultation, you agree to these terms and any applicable written agreement. If you act for an organization, you confirm that you are authorized to bind it."], items: ["Website usage", "Professional services", "Software solutions", "Consultations and demonstrations"] },
    { id: "services", title: "Services Overview", paragraphs: ["Brainzon provides enterprise software products and digital transformation services. Availability, scope, deliverables, and service levels are defined in the relevant commercial agreement."], items: ["BrainERP", "BrainCRM", "BrainAI", "BrainConnect", "ERP implementation", "Custom software development", "Legacy modernization services", "Cloud solutions"] },
    { id: "customer-responsibilities", title: "Customer Responsibilities", paragraphs: ["Customers must cooperate reasonably with delivery activities and ensure that their use of Brainzon services is lawful, authorized, and secure."], items: ["Provide accurate and complete information", "Maintain account and credential security", "Follow applicable laws and regulations", "Use services responsibly and within agreed limits"] },
    { id: "intellectual-property", title: "Intellectual Property", paragraphs: ["Brainzon and its licensors retain rights in Brainzon software, branding, website content, documentation, methods, and proprietary technology. Customers retain ownership of their data and customer-specific materials, subject to licenses reasonably required to provide the services.", "Ownership and usage rights for custom deliverables are governed by the applicable statement of work or service agreement."], groups: [{ title: "Brainzon property", items: ["Software and product platforms", "Branding and trademarks", "Website content and documentation", "Proprietary technology and methods"] }, { title: "Customer property", items: ["Customer data", "Customer-provided and customer-specific materials"] }] },
    { id: "software-usage", title: "Software Usage", paragraphs: ["Software access is licensed, not sold, unless an agreement expressly states otherwise. Users may not exceed license scope, bypass technical controls, interfere with service operation, or use software for unlawful purposes."], items: ["Comply with applicable license scope", "Do not share access without authorization", "Do not copy or exploit software without permission", "Do not reverse engineer except where a restriction is prohibited by law"] },
    { id: "commercial-terms", title: "Payment and Commercial Terms", paragraphs: ["Pricing, currency, taxes, billing schedules, renewal terms, expenses, and payment obligations are specified in the applicable proposal, order form, subscription, or service agreement. Late or disputed payments are handled under that agreement."], items: ["Project pricing", "Subscription fees", "Payment obligations", "Service-specific commercial agreements"] },
    { id: "availability", title: "Service Availability", paragraphs: ["Brainzon designs and operates services for enterprise reliability, but uninterrupted or error-free availability cannot be guaranteed. Maintenance, third-party services, internet conditions, security events, and circumstances beyond reasonable control may affect availability. Contractual service levels, where offered, are defined separately."] },
    { id: "liability", title: "Limitation of Liability", paragraphs: ["To the maximum extent permitted by applicable law, each party's liability is subject to the limitations and exclusions stated in the applicable commercial agreement. Brainzon is not liable for indirect, incidental, special, exemplary, or consequential losses—including lost profits, revenue, data, or business opportunity—except where such exclusion is prohibited by law.", "Nothing in these terms excludes liability that cannot lawfully be excluded. Specific negotiated agreements may establish different limits and will take precedence."] },
    { id: "termination", title: "Termination", paragraphs: ["Access or services may be suspended or terminated according to an applicable agreement, after material breach and any required cure period, or where continued service would create legal, security, or operational risk."], items: ["Material contract violation", "Non-payment of undisputed amounts", "Legal or regulatory requirements", "Misuse that threatens systems, data, or other users"] },
    { id: "governing-law", title: "Governing Law", paragraphs: [`These terms and related disputes are governed by ${legalCompany.governingLaw}, without regard to conflict-of-law principles. The applicable agreement may also specify venue, dispute resolution, or arbitration requirements.`] },
  ],
};

const securityPolicy: LegalDocument = {
  slug: "security-policy", title: "Security Built Into Every Solution", subtitle: "Brainzon follows security-first principles to protect business applications, data, and digital infrastructure.",
  description: "Learn how Brainzon protects customer data through secure architecture, access controls, monitoring, and enterprise security practices.", lastUpdated: legalCompany.lastUpdated,
  introduction: "Security is a shared and continuous responsibility. Brainzon applies risk-based safeguards across architecture, development, delivery, and operations, with controls adapted to each solution, deployment model, and customer agreement.",
  sections: [
    { id: "security-philosophy", title: "Security Philosophy", paragraphs: ["We integrate security considerations into solution design and delivery rather than treating them as a final-stage activity. Our objective is to protect customer data, support resilient enterprise operations, and continuously improve controls as risks evolve."], items: ["Security by design", "Protection of customer and business data", "Reliable enterprise architecture and operations"] },
    { id: "application-security", title: "Application Security", paragraphs: ["Application controls are selected according to architecture, data sensitivity, exposure, and customer requirements."], items: ["Secure coding standards and developer guidance", "Peer review and change controls", "Vulnerability identification and remediation", "Dependency and software supply-chain monitoring"] },
    { id: "data-protection", title: "Data Protection", paragraphs: ["We use layered safeguards designed to preserve data confidentiality, integrity, and availability throughout its lifecycle."], items: ["Encryption in transit using appropriate protocols", "Encryption at rest where supported and appropriate", "Protected backup and recovery processes", "Data access controls based on approved roles"] },
    { id: "infrastructure-security", title: "Infrastructure Security", paragraphs: ["Infrastructure safeguards depend on the selected cloud, private-cloud, or customer-managed deployment model and the responsibilities defined in the service agreement."], items: ["Cloud security configuration and hardening", "Network protection and segmentation", "Operational monitoring and alerting", "Availability, backup, and recovery practices"] },
    { id: "identity-access", title: "Identity and Access Management", paragraphs: ["Access is managed according to business need and the principle of least privilege."], items: ["Role-based access control", "Least-privilege access", "Appropriate authentication mechanisms", "User provisioning, review, and removal processes"] },
    { id: "secure-sdlc", title: "Secure Software Development Lifecycle", paragraphs: ["Security activities are integrated across the delivery lifecycle and calibrated to solution risk."], items: ["Planning: identify security and privacy requirements", "Design: model trust boundaries and controls", "Development: apply secure engineering practices", "Testing: validate functionality and security", "Deployment: use controlled release processes", "Monitoring: observe, respond, and improve"] },
    { id: "ai-security", title: "AI Security", paragraphs: ["BrainAI solutions are designed with enterprise privacy and access boundaries in mind. Customer-specific architecture determines model providers, data flows, retention, and human oversight."], items: ["Responsible AI practices", "Protection of prompts, documents, and business data", "Model and feature access controls", "Enterprise privacy and data-use considerations"] },
    { id: "incident-response", title: "Incident Response", paragraphs: ["Brainzon maintains an incident-handling approach designed to identify, manage, and learn from suspected security events. Notification obligations are handled according to applicable law and customer agreements."], items: ["Detection", "Analysis and prioritization", "Containment", "Recovery", "Post-incident improvement"] },
    { id: "customer-responsibilities", title: "Customer Security Responsibilities", paragraphs: ["Security outcomes also depend on customer-controlled users, devices, configurations, integrations, and operating environments."], items: ["Protect credentials and authentication factors", "Manage user access and permissions", "Apply recommended configuration and update practices", "Report suspected security concerns promptly"] },
    { id: "report-security-issues", title: "Report Security Issues", paragraphs: [`Report a suspected vulnerability to ${legalCompany.securityEmail}. Include the affected service, a clear description, reproduction steps where safe, and contact details for coordinated follow-up.`, "Please avoid accessing, altering, or retaining data that does not belong to you; disrupting services; or publicly disclosing an issue before Brainzon has had a reasonable opportunity to investigate and remediate. We will acknowledge good-faith reports and coordinate responsible disclosure where appropriate."], groups: [{ title: "Security contact", items: [legalCompany.securityEmail] }] },
  ],
};

export const legalDocuments = { "privacy-policy": privacyPolicy, "terms-of-service": termsOfService, "security-policy": securityPolicy } as const satisfies Record<LegalDocument["slug"], LegalDocument>;
